version: "3"
services:
  db:
    image: postgres:10-alpine
    container_name: library-api-db
    volumes:
      - /var/lib/docker/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=library_api
      - POSTGRES_PASSWORD=postgres
    networks:
      - nginx-network
  server:
    image: library-api-release
    container_name: library-api-server
    command: swift run Run --env=production
    ports:
      - "8080:80"
    networks:
      - nginx-network
    depends_on:
      - db
volumes:
  postgres-data:
networks:
  nginx-network:
    external: true